version: 0.0
os: linux

files:
  - source: build/libs
    destination: /home/ubuntu/app
    overwrite: yes

  - source: scripts
    destination: /home/ubuntu/app/scripts
    overwrite: yes

permissions:
  - object: /home/ubuntu/app
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60

  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 60

  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
